metros = float(input('Medida em metros: '))
print(f'A medida de {metros}m equivale a:')
print(f'{metros/1000}km')
print(f'{metros/100}hm')
print(f'{metros/10}dam')
print(f'{metros*10}dm')
print(f'{metros*100}cm')
print(f'{metros*1000}mm')
